# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Person.create!(name: 'Pshtewan Kamal', role: 'Web Designer and Researcher', about: 'Pshtewan Kamal Babakir manages DidiMn, a cultural website in Kurdistan. Babakir managed Cinema in SulyOn, the first Kurdish cultural website. Since 2008, he has been a member of the Sebar Theater Group, which has performed in Sulaimani University and in the Sulaimani streets. He has directed two documentaries for KNN, a regional television channel and has acted in a documentary on a theatrical adaptation of Sherko Bekas’ book-length poem Now a Girl is My Homeland. In 2014, the Sulaimani Poets’ Game recognized him as a poet of merit. His publications include The Loch Raven Review. He will graduate from the American University of Iraq, Sulaimani (AUIS) in December of 2016 as an IT and Web Development Major and a Minor in English Literature. He is now a videographer, photographer, and research assistant at Kashkul.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
# Person.create!(name: 'Shene Mohammad', role: 'Project Coordinator', about: 'Shene Mohammed is currently Lead Translator, Interpreter, and Research Assistant at Kashkul. Mohammed has been instrumental in bringing the fifteen major Kurdish classical poets of the 19th century into English, an on-going project. She interned for the Communication Office at the American University of Iraq, Sulaimani (AUIS), where she will graduate as an Engineering Major in 2017. She is also a translator at DidiMn, a Kurdish cultural website.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
# Person.create!(name: 'Halo Fariq', role: 'Translator', about: 'Halo Fariq studies English at Sulaimani University. He has translated for Chawder, a weekly newspaper and DidiMn, a cultural website. Fariq has also subtitled movies for Salim Cinema and an animated movie for Zaro TV. He has also translated a novel, Kent Haruf’s Our Souls At Night, from English to Kurdish (forthcoming in 2017). He volunteers at the Hiwa Hospital for Kids with Cancer and serves as a member of the Peshmerga, Kurdish fighting forces. Fariq currently works as a translator for Kashkul, bringing Sherko Bekas’ Now a Girl is a Homeland into English.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
# Person.create!(name: 'Lana Khalid', role: 'Translator', about: 'Lana Khalid grew up speaking Arabic, Kurdish, and English. Kamaran received her BA in English-Journalism from The American University of Iraq, Sulaimani (AUIS) in 2016. She received the Dean’s Award twice as well as the President’s Award for academic performance. She volunteers at the Kanakawa Refugee Camp teaching young Yezidi girls English and critical thinking. Kamaran currently works as a translator with Kashkul and a translation officer at SREO Consulting.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
# Person.create!(name: 'Lazha Taha', role: 'Photographer and Videographer', about: 'Lazha Taha Mahmood is currently a reporter and manger of journalism at DidiMn, a Kurdish cultural website. Mahmood was a reporter at SulyOn, the first Kurdish cultural website until DidiMn. She is a senior in The University of Sulaimani in the Media Studies Department. Mahmood works for Kashkul and other organizations as a photographer and videographer.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
# Person.create!(name: 'Mohammed Fatih', role: 'Researcher and Translator', about: 'Mohammed Fatih Mohammed was born into a devout Kurdish Sufi family in Qaradagh. He will graduate with a major in Business Administration and minor Middle Eastern Studies at the American University of Iraq, Sulaimani (AUIS) in 2013. Mohammed worked as a translator on classical Kurdish poetry and now studies and translates Kurdish Jihadist poetry as part of a larger research project on concepts of Jihad in the KRG. He is part of on-going efforts to create a counter-terrorism center at AUIS. He speaks Kurdish, Arabic, Turkish, and English and has formal training in reading and studying the Quran and Quranic sciences.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
# Person.create!(name: 'Savan Ako', role: 'Translator', about: 'Savan A. Ahmad is an undergraduate in the Administration and Economic Department at the University of Sulaimani where she majors in Accounting. Ahmad is the Translation Supervisor at DidiMn as well as a member of 68, a youth organization. She also subtitles movies for Salim cinema. She participated in gallery shows for her paintings at a very young age and continues to draw and paint today. She currently works as a translator at Kashkul where she focuses on bringing the fifteen major Kurdish classical poets of the 19th century into English, an on-going project.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
# Person.create!(name: 'Heran Sherko', role: 'Translator', about: 'She graduated from AUIS with a degree in Information Technology. At AUIS, she received the Dean’s Award, an award for highest GPA in her IT cohort, and awards for being an exceptional tutor for Civilization courses. She has worked with Kashkul on collection, digitization, and preparation of exhibits. She is interested in computer science, particularly database studies and map making.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
# Person.create!(name: 'Ali Adnan', role: 'Translator', about: 'Ali Adnan Mohammed graduated from AUIS with a degree in International Studies and works at the newly established Al-Bayan University in Baghdad. During his university life, he learned the importance of research and history and believes that both fields, if applied correctly, will play a role in developing underdeveloped countries. His father represents the spark of hope, motivation, and inspiration; he dedicates this work to him.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
# Person.create!(name: 'Marie LaBrosse', role: 'Co-Founder and Co-Director', about: 'Alana Marie Levinson-LaBrosse is a translator, poet and teacher who has worked in Iraq for the last six years, serving as the founding Chair of the English Department at the American University of Iraq, Sulaimani (AUIS). She received her MFA at Warren Wilson and MEd from the University of Virginia. Handful of Salt (The Word Works, 2016) introduced Kajal Ahmad’s poetry to English. New and Selected Poems of Abdulla Pashew is forthcoming from Phoneme Media in 2017. Translations and essays have appeared in The Iowa Review, Words Without Borders, Poetry Society of America, and the anthology: SoJust. Levinson-LaBrosse is currently a Research Fellow at AUIS’ Institute for Regional and International Studies (IRIS), a PhD candidate at the University of Exeter’s Centre for Kurdish Studies, and the Co-Founder and Co-Director of Kashkul.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
# Person.create!(name: 'Elizabeth Campbell', role: 'Co-Founder and Co-Director', about: 'Dr. Elizabeth Campbell is an historian of the Middle East. She received her MA and PhD in history from the University of Washington and her BA from the University of California, Berkeley. She was an Assistant Professor at the American University of Iraq, Sulaimani from 2012 to 2016 and was chair of the Department of Social Sciences from 2013 to 2015. Campbell is fluent in Arabic and her research focuses on Christianity and Islam in late antique and early Islamic Mesopotamia. She is currently an Assistant Professor of History at Daemen College in Amherst, New York. She is a Research Fellow at AUIS’ Institute for Regional and International Studies (IRIS) and the Co-Founder and Co-Director of Kashkul.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')

# 10.times do
# 	Event.create!(name: 'Event for Stuff', date: 'January 19, 2016', description: 'This was an event that was for stuff. We did some really cool stuff, and it was a lot of fun. Lots of fun. Fun fun fun. Really cool event. We did some cool stuff. It was an event. You should have been there; you missed out. Loser.')
# end

# Project.create!(name: 'Krok - Crux', description: 'As violent extremism becomes more common throughout the world, understanding becomes more scarce. Crux strives to comprehend extremism in Iraq and its Kurdish regions, in its violent and nonviolent forms, by translating influential poetry of jihadist leaders, interviewing and translating the archives of regional Islamic notables, interviewing families who have lost children to the Islamic State, interviewing prisoners of religious conviction. The main effort of this project is to get to know devotion in all the contemporary Kurdish manifestations, to shed light on how devotion becomes violent but also how it can remain or become once again peaceful. As this project has ramifications for American and Kurdish audiences alike, it has a corollary title in Kurdish, “Krok.” We have translated that as “crux,” but other resonant meanings are “core,” “seed,” and “essence.”', authors: 'Mohammed Fatih, Rebaz Majeed, Halo Fariq, Alana Marie Levinson-LaBrosse')
# Project.create!(name: 'Mosul Remembered', description: 'The Islamic State has forever changed Mosul. As much as a city is its landmarks and streets, it is the people who live and have lived there. Whatever Mosul became under the Islamic State’s occupancy, there is a Mosul that lives in on in the minds of the people who have made it a city for decades. Before that city of memory is lost, we will visit the recently formed camps for internally displaced people (IDPs) from Mosul. In teams of three (researcher, interpreter, videographer/photographer), we will conduct interviews, asking former residents to remember their city, the Mosul they knew. We will ask each interviewee to draw maps and images that alongside their interviews will create a digital memory-map: Mosul Remembered.', authors: 'Lana Kamaran, Briyar Bahha, Elizabeth Campbell, Alana Marie Levinson-LaBrosse, Scott McCoubrey, Pshtewan Kamal, Lazha Taha, Shene Mohammed')
# Project.create!(name: 'Talabani Tekiye', description: 'Not 30 kilometers away from the Islamic State’s front lines, the Talabani Tekiye and Mosque of Kirkuk is and has been a bastion of liberal Islam. Since the early 1800’s, the Talabani family has offered sermons and prayers in every language of the city, including Turkish, Arabic, Farsi, Turcoman, and Kurdish. Too, both women and men serve the devotees as mullahs. Men, women, and children perform the traditional devotions of Sufis. The tekiye has welcomed in Kashkul researchers to study the theology and practice of this place and how, over generations, people have created and preserved as sense of openness in heart and mind. ', authors: 'Shene Mohammed, Pshtewan Kamal, Lazha Taha, Mohammed Fatih, Alana Marie Levinson-LaBrosse, Pshtewan Kamal and Lazha Taha')
# Project.create!(name: '19th Century Kurdish Poetry', description: 'As the last independent Kurdish principalities fall to Ottoman and Persian rule, poetry’s politics and economics shift dramatically. Without the Babans and the Ardalans, there is no Kurdish court to finance poets and implicitly dictate their subject matter. The court, once the foundation of how poets got paid, vanishes and the profession of “court poet,” once a steady career path, disappears. This both impoverishes and frees poets. The Kurdish poet of the 19th century has no prince to praise, no prince’s enemy to curse; he has only himself and whatever he chooses to govern him. This breaks 19th century Kurdish poetry wide open: subject matter ranges from pioneering articulations of animal rights to critical examinations of Islam to explicit curses intended to anger, to amuse, to seduce. The generation of Kurdish poets formed as the reigns of the Babans and the Ardalans comes to a close bear their grief by embracing the sudden, shocking freedom of being their poetry’s own prince. This project focuses on bringing these predominantly Sorani Kurdish poems to English.', authors: 'Shene Mohammed, Savan Abdulrahman, Lana Kamaran, Mohammed Fatih, Srusht Barzan, Alana Marie Levinson-LaBrosse')
# Project.create!(name: 'Sherko Bekas', description: 'Sherko Bekas grew up alongside the Political Union of Kurdistan (PUK), a powerful political party in the Kurdish Regional Government (KRG). What is now “the state” was once a Kurdish guerrilla force, the peshmerga, in which Bekas served shoulder-to-shoulder with future political leaders. Both poet and politician survived on bright ideals. As time passed, disappointment arrived: nepotism became common, meritocracy struggled to take hold, educational and health reforms were slow, women’s rights arrived, but were not fully realized. Sherko felt the need to articulate the collision between revolution and governing. Reacting against a Turkish or Arab government, the artist reinforces rather than puts at risk his or her Kurdishness. Criticizing a Kurdish state for which one fought is not only delicate, but heart-breaking. More, the two traditionally significant parties, the Patriotic Union of Kurdistan (PUK) and the Kurdistan Democratic Party (KDP), have financially backed their preferred poets, further complicating an artist’s ability or desire to find fault. In a region where neither academia nor publishing (copyright is not enforced) can sustain poets, party funding has been crucial income. With many reasons to stay silent, Sherko spoke. Over the course of his life, he abandoned political subject matter and championed a broken free verse. These are culturally dramatic statements from a man who wrote the PUK anthem, militaristic in its rhetoric and meter. In 2011, he punctuated the rift by publishing the controversial “Now A Girl Is My Homeland,” a book that oriented the poet away from the traditional concepts of “homeland” and toward the emerging idea that a lover could be one’s entire homeland. This project attempts to show the shift in Bekas’ verse from his early to late work as well as to bring the entirety of “Homeland” into English for the first time.', authors: 'Halo Fariq and Alana Marie Levinson-LaBrosse')
# Project.create!(name: 'Kurdish Film Archive', description: 'The project that we are aiming for is to archive the history of Kurdish Cinema. Where and when Kurdish Cinema started, and where it comes from? We explore the Kurdish filmmakers work, and do they considered as Kurdish films? If not, why? If yes, why? Kurdish Cinema has divided into more than five parts in the world because Kurdish filmmakers live in many different places, and they have been influenced by European, American and other countries’ cinema. Cinema for all nations is like a language. It should be standardized, if not, their cinema will not have an identity, and does not represent the nation’s culture.', authors: 'Pshtewan Kamal')
# Project.create!(name: 'Kurdish Painting Archive', description: 'In this century, one of the most important tools that make things reach into the hands of audiences is that we can digitize anything. We as Kurds have many great artists, and they have done many great art works, but the paintings can’t be reached into the hands of the audiences from around the world. In the first step, we collect as many paintings as we can from painters in Kurdistan with information about paintings such as: the size of the painting, the material has been used, when the painting has been painted and where, the description of the painting, who painted it and who owns it, and finally in which exhibition it has been exhibited. The next step after archiving is to digitize this project for marketing purposes.', authors: 'Pshtewan Kamal, Savan Ako and Lazha Taha')
# Project.create!(name: 'Kurdish Music Video', description: 'What we do in this project is to bring the attention back to the importance of music by doing good quality Music Video Clips for the Kurdish musicians.', authors: 'Pshtewan Kamal and Lazha Taha')

Admin.create email: 'kashkuldev@gmail.com', password: 'password'