# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Person.create!(name: 'Pshtewan Kamal', role: 'Web Designer and Researcher', about: 'Pshtewan Kamal Babakir manages DidiMn, a cultural website in Kurdistan. Babakir managed Cinema in SulyOn, the first Kurdish cultural website. Since 2008, he has been a member of the Sebar Theater Group, which has performed in Sulaimani University and in the Sulaimani streets. He has directed two documentaries for KNN, a regional television channel and has acted in a documentary on a theatrical adaptation of Sherko Bekas’ book-length poem Now a Girl is My Homeland. In 2014, the Sulaimani Poets’ Game recognized him as a poet of merit. His publications include The Loch Raven Review. He will graduate from the American University of Iraq, Sulaimani (AUIS) in December of 2016 as an IT and Web Development Major and a Minor in English Literature. He is now a videographer, photographer, and research assistant at Kashkul.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
Person.create!(name: 'Shene Mohammad', role: 'Project Coordinator', about: 'Shene Mohammed is currently Lead Translator, Interpreter, and Research Assistant at Kashkul. Mohammed has been instrumental in bringing the fifteen major Kurdish classical poets of the 19th century into English, an on-going project. She interned for the Communication Office at the American University of Iraq, Sulaimani (AUIS), where she will graduate as an Engineering Major in 2017. She is also a translator at DidiMn, a Kurdish cultural website.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
Person.create!(name: 'Halo Fariq', role: 'Translator', about: 'Halo Fariq studies English at Sulaimani University. He has translated for Chawder, a weekly newspaper and DidiMn, a cultural website. Fariq has also subtitled movies for Salim Cinema and an animated movie for Zaro TV. He has also translated a novel, Kent Haruf’s Our Souls At Night, from English to Kurdish (forthcoming in 2017). He volunteers at the Hiwa Hospital for Kids with Cancer and serves as a member of the Peshmerga, Kurdish fighting forces. Fariq currently works as a translator for Kashkul, bringing Sherko Bekas’ Now a Girl is a Homeland into English.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
Person.create!(name: 'Lana Khalid', role: 'Translator', about: 'Lana Khalid grew up speaking Arabic, Kurdish, and English. Kamaran received her BA in English-Journalism from The American University of Iraq, Sulaimani (AUIS) in 2016. She received the Dean’s Award twice as well as the President’s Award for academic performance. She volunteers at the Kanakawa Refugee Camp teaching young Yezidi girls English and critical thinking. Kamaran currently works as a translator with Kashkul and a translation officer at SREO Consulting.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
Person.create!(name: 'Lazha Taha', role: 'Photographer and Videographer', about: 'Lazha Taha Mahmood is currently a reporter and manger of journalism at DidiMn, a Kurdish cultural website. Mahmood was a reporter at SulyOn, the first Kurdish cultural website until DidiMn. She is a senior in The University of Sulaimani in the Media Studies Department. Mahmood works for Kashkul and other organizations as a photographer and videographer.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
Person.create!(name: 'Mohammed Fatih', role: 'Researcher and Translator', about: 'Mohammed Fatih Mohammed was born into a devout Kurdish Sufi family in Qaradagh. He will graduate with a major in Business Administration and minor Middle Eastern Studies at the American University of Iraq, Sulaimani (AUIS) in 2013. Mohammed worked as a translator on classical Kurdish poetry and now studies and translates Kurdish Jihadist poetry as part of a larger research project on concepts of Jihad in the KRG. He is part of on-going efforts to create a counter-terrorism center at AUIS. He speaks Kurdish, Arabic, Turkish, and English and has formal training in reading and studying the Quran and Quranic sciences.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
Person.create!(name: 'Savan Ako', role: 'Translator', about: 'Savan A. Ahmad is an undergraduate in the Administration and Economic Department at the University of Sulaimani where she majors in Accounting. Ahmad is the Translation Supervisor at DidiMn as well as a member of 68, a youth organization. She also subtitles movies for Salim cinema. She participated in gallery shows for her paintings at a very young age and continues to draw and paint today. She currently works as a translator at Kashkul where she focuses on bringing the fifteen major Kurdish classical poets of the 19th century into English, an on-going project.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
Person.create!(name: 'Heran Sherko', role: 'Translator', about: 'She graduated from AUIS with a degree in Information Technology. At AUIS, she received the Dean’s Award, an award for highest GPA in her IT cohort, and awards for being an exceptional tutor for Civilization courses. She has worked with Kashkul on collection, digitization, and preparation of exhibits. She is interested in computer science, particularly database studies and map making.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
Person.create!(name: 'Ali Adnan', role: 'Translator', about: 'Ali Adnan Mohammed graduated from AUIS with a degree in International Studies and works at the newly established Al-Bayan University in Baghdad. During his university life, he learned the importance of research and history and believes that both fields, if applied correctly, will play a role in developing underdeveloped countries. His father represents the spark of hope, motivation, and inspiration; he dedicates this work to him.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
Person.create!(name: 'Marie LaBrosse', role: 'Co-Founder and Co-Director', about: 'Alana Marie Levinson-LaBrosse is a translator, poet and teacher who has worked in Iraq for the last six years, serving as the founding Chair of the English Department at the American University of Iraq, Sulaimani (AUIS). She received her MFA at Warren Wilson and MEd from the University of Virginia. Handful of Salt (The Word Works, 2016) introduced Kajal Ahmad’s poetry to English. New and Selected Poems of Abdulla Pashew is forthcoming from Phoneme Media in 2017. Translations and essays have appeared in The Iowa Review, Words Without Borders, Poetry Society of America, and the anthology: SoJust. Levinson-LaBrosse is currently a Research Fellow at AUIS’ Institute for Regional and International Studies (IRIS), a PhD candidate at the University of Exeter’s Centre for Kurdish Studies, and the Co-Founder and Co-Director of Kashkul.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')
Person.create!(name: 'Elizabeth Campbell', role: 'Co-Founder and Co-Director', about: 'Dr. Elizabeth Campbell is an historian of the Middle East. She received her MA and PhD in history from the University of Washington and her BA from the University of California, Berkeley. She was an Assistant Professor at the American University of Iraq, Sulaimani from 2012 to 2016 and was chair of the Department of Social Sciences from 2013 to 2015. Campbell is fluent in Arabic and her research focuses on Christianity and Islam in late antique and early Islamic Mesopotamia. She is currently an Assistant Professor of History at Daemen College in Amherst, New York. She is a Research Fellow at AUIS’ Institute for Regional and International Studies (IRIS) and the Co-Founder and Co-Director of Kashkul.', facebook: 'http://facebook.com', twitter: 'http://twitter.com', instagram: 'http://instagram.com')

10.times do
	Event.create!(name: 'Event for Stuff', date: 'January 19, 2016', description: 'This was an event that was for stuff. We did some really cool stuff, and it was a lot of fun. Lots of fun. Fun fun fun. Really cool event. We did some cool stuff. It was an event. You should have been there; you missed out. Loser.')
end